### ISSUE TITLE
Улучшить задание

### ISSUE THREAD

**Issue by VadimCpp** [KazanExpress/frontend-test-task#6]
Список улучшений:
1. Все дебильные смайлы 😉вынести в раздел "Для тех, кто не любит формальности" 😉😉😉😉😉😉😉😉😉😉
2. Заменить текст `Если вы нашли его случайно - попробуйте сделать!` на `Даже если Вы нашли задание случайно, предлагаем выполнить его!`
3. Заменить текст `Авось и вас к себе возьмём.😉` на `Мы с радостью проверим Ваше задание, дадим Вам развернутую обратную связь, и, возможно, предложим Вам сотрудничество` 😉😉😉😉😉😉😉😉😉😉😉😉😉😉😉😉😉😉😉😉😉😉😉😉😉😉😉😉😉😉😉😉😉😉😉😉😉😉😉😉😉😉😉😉😉😉😉😉😉😉😉😉😉😉😉😉😉😉😉😉😉😉😉😉😉😉😉😉😉😉😉😉😉😉😉😉😉😉😉😉

**Comment by Raiondesu** [comment]
Спасибо за инициативу, конечно, но грубить не стоит, даже если не нравится стилистика.
Мы вас услышали.
